### ISSUE TITLE
Keep Sensitive data into .env file 

### ISSUE THREAD

**Issue by sudip-khanal** [samikshakhadka/PoetryApp#1]
Remove the static data from your settings.py file 

EMAIL_HOST_USER = 'smartattendance64@gmail.com'
EMAIL_HOST_PASSWORD = 'nzyqgajzftruczmf' #env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL =  'smartattendance64@gmail.com' #env('DEFAULT_FROM_EMAIL')

Replace above line and use environment variable 
example:

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER=env('G_MAIL')
EMAIL_HOST_PASSWORD =env('GMAIL_PASS')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = env('G_MAIL')
SITE_URL = env('SITE_URL')

**Comment by samikshakhadka** [comment]
it's good
